"""Mapeamento canônico de colunas para cada fonte de dados."""

MTO_MAP = {
    "Area / Discipline":             "area_code",
    "ZONE":                          "zone",
    "Pipe Name":                     "line_tag",
    "3D Item Name":                  "item_3d_name",
    "3D Type":                       "item_3d_type",
    "Diâmetro 1 (pol.)":             "diameter_nom_in",
    "Diâmetro 2 (pol.)":             "diameter_sec_in",
    "Comprimento de Tubo (mm)":      "pipe_length_mm",
    "Descritivo":                    "description",
    "Especificação de Material":     "material_spec",
    "Código de Material Padrão":     "material_code_std",
    "Código de Material Alternativo":"material_code_alt",
    "Posição":                       "position",
    "Elevação (mm)":                 "elevation_mm",
    "Peso (kg)":                     "weight_kg",
    "Área Superfície Externa (mm2)": "surface_area_mm2",
    "Isométrico da Linha":           "isometrico",
    "Texto no Isométrico":           "isometric_text",
    "Spool Number":                  "spool_number_raw",
    "Escopo":                        "scope",
}

SGS_MAP = {
    "unid":                          "unit_code",
    "subunid":                       "sub_unit",
    "isometrico + - + spool":        "spool_key_raw",
    "fabricante":                    "manufacturer",
    "tp_linha":                      "line_type",
    "linha":                         "line_tag",
    "fluido":                        "fluid",
    "revisao":                       "revision",
    "mat":                           "material",
    "diametro":                      "diameter_mm",
    "dipol":                         "diameter_in",
    "esp":                           "thickness_mm",
    "hold":                          "hold",
    "espec":                         "spec",
    "comp":                          "length_m",
    "area":                          "area_m2",
    "peso":                          "weight_kg",
    "TIPO":                          "scope",
    "progfab":                       "pct_fab",
    "dtlibfab":                      "dt_lib_fab",
    "dtcort":                        "dt_corte",
    "ajudat":                        "dt_acoplamento",
    "soldat":                        "dt_soldagem",
    "vsdat":                         "dt_vs",
    "libdat":                        "dt_lib_end",
    "dtpint":                        "dt_pintura",
    "DTEMBARQUE":                    "dt_embarque",
    "dtlibmon":                      "dt_lib_mon",
    "PROGMON":                       "pct_mon",
    "dtprogmon":                     "dt_prog_mon",
    "dtpremon":                      "dt_pre_mon",
    "dtposmon":                      "dt_montagem",
    "sthdat":                        "dt_sth",
    "lavdat":                        "dt_lavagem",
    "sger":                          "sger",
    "tjs":                           "joints_total",
}

VALVES_MAP = {
    "ID":               "valve_id_raw",
    "ID+I":             "valve_tag",
    "Descrição do Item":"description",
    "DN":               "dn_mm",
    "Peso Unit":        "unit_weight_kg",
    "Qtd Prev":         "qty_planned",
    "Qtd Recebida":     "qty_received",
    "Peso Previsto":    "weight_planned_kg",
    "Peso Recebido":    "weight_received_kg",
    "DISPONIVEL":       "availability",
    "RESV QTY":         "qty_reserved",
    "ISSUE QTY":        "qty_issued",
}

JOINTS_EXCEL_MAP = {
    "UNID":             "unit_code",
    "subunid":          "sub_unit",
    "STH":              "sth",
    "isometrico":       "isometrico",
    "spool":            "spool",
    "junta":            "junta",
    "linha":            "line_tag",
    "espec":            "spec",
    "fluido":           "fluid",
    "P_C":              "pressure_class",
    "tipo":             "joint_type",
    "diam":             "diameter_mm",
    "POL":              "diameter_in",
    "esp":              "thickness_mm",
    "MAT":              "material",
    "NI":               "insp_level",
    "TT":               "requires_tt",
    "DU":               "requires_ut",
    "progfab":          "pct_fab",
    "dtcort":           "dt_corte",
    "dtaju":            "dt_acoplamento",
    "dtsold":           "dt_soldagem",
    "asraiz":           "welder_root_sin",
    "asench":           "welder_fill_sin",
    "corrida1":         "corrida_1",
    "corrida2":         "corrida_2",
    "corrida3":         "corrida_3",
    "corrida4":         "corrida_4",
    "dtVS":             "dt_vs",
    "RX_US":            "ndt_method",
    "dt_lib_END":       "dt_lib_end",
    "DTEMBARQUE":       "dt_embarque",
    "dtprogmon":        "dt_prog_mon",
    "dtpremon":         "dt_pre_mon",
    "dtposmon":         "dt_montagem",
    "HT_NUMBER1":       "heat_number_1",
    "HT_NUMBER2":       "heat_number_2",
    "sger":             "status_raw",
    "IEIS":             "ieis",
}

# Mapeamento dos códigos sger → enum joint_status
SGER_TO_STATUS = {
    "01": "01_NAO_INICIADA",
    "03": "03_AGUARD_ACOPLAMENTO",
    "04": "04_AGUARD_SOLDAGEM",
    "09": "09_AGUARD_VS",
    "12": "12_AGUARD_LP_PM",
    "14": "14_AGUARD_LIB_LOTE",
    "15": "15_AGUARD_RX_US",
    "18": "18_AGUARD_RX_REPARO",
    "23": "23_AGUARD_TT",
    "30": "30_LIBERADA",
}
